DEFINE LITERAL $01
DEFINE ZEROPAGE $A0
DEFINE ABSOLUTE $A000
DEFINE ADDRESS1 ZEROPAGE
DEFINE ADDRESS2 ABSOLUTE
DEFINE A000 $03

lda A000,X
ADC #literal
lda ZEROPAGE
lda ABSOLUTE
lda address1,X
lda address2,Y
